services:
  webserver:
    image: httpd:trixie
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docs:/usr/local/apache2/htdocs/"
      - "./nfs:/nfs"
      - "./fstab:/etc/fstab"
      - "./rockyou.txt:/mnt/rockyou.txt"
    command: bash -c "(apt update && apt install sudo curl iputils-ping nfs-common hydra ftp wget libwebsockets-dev openssh-client binutils iputils-ping iproute2 nmap -y && useradd appuser && mkdir /home/appuser && chown appuser:appuser /home/appuser && cd /  && sudo -H -u appuser bash -c 'wget -O /home/appuser/ttyd.aarch64 https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64 && chmod u+x /home/appuser/ttyd.aarch64 && /home/appuser/ttyd.aarch64 -i eth0 -p 8080 -W bash &') && mount -a && curl -d 'server online' ntfy.sh/networking-sm4ai1 && httpd-foreground"
