services:
  webserver:
    image: httpd:trixie
    privileged: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docs:/usr/local/apache2/htdocs/"
      - "./nfs:/nfs"
      - "./fstab:/etc/fstab"
    command: bash -c "(apt update && apt install wget openssh-server nfs-common libwebsockets-dev iproute2 inetutils-ping -y && cd / && wget https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64 && chmod u+x /ttyd.aarch64 && /ttyd.aarch64 -i eth0 -p 8080 -W bash &) && httpd-foreground"
